Add `quick` arg to sacrifice optimal behaviors for quicker execution
Loathing-Associates-Scripting-Society/garbage-collector pull request #1094
Opened 2022-09-18 18:00 UTC by Rinn

Only change currently is to instead use historical price rather than getSalePrice if the prices are less than a week old, for only items that will be sold.

2022-09-18 18:23 UTC, horrible-little-slime approved these changes
Is this tested? It looks generally good

2022-09-18 18:26 UTC, Rinn commented
I'll test this after rollover, i'm in the middle of a run atm

2022-09-19 05:19 UTC, Rinn commented
I'll follow up after it finishes running, but it did blitz through all the dailies super fast, most notably not searching for anything when it open cargo shorts. The only thing I think may cause issue is the 50k maximize limit and the longer maximize query because of all the -equip brimstone, but i'll know more later.

2022-09-19 05:39 UTC, horrible-little-slime commented
Can/should we closet brimstone instead? I guess if we do that we should do
papier mache as well

On Mon, Sep 19, 2022, 1:20 AM Joe Kirchoff ***@***.***> wrote:

> I'll follow up after it finishes running, but it did blitz through all the
> dailies super fast, most notably not searching for anything when it open
> cargo shorts. The only thing I think may cause issue is the 50k maximize
> limit and the longer maximize query because of all the -equip brimstone,
> but i'll know more later.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/pull/1094#issuecomment-1250581280>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASZNQVLLS33C6WCBHICQUVLV67ZYLANCNFSM6AAAAAAQPRHCSA>
> .
> You are receiving this because your review was requested.Message ID:
> <Loathing-Associates-Scripting-Society/garbage-collector/pull/1094/c1250581280
> @github.com>
>

2022-09-19 05:57 UTC, Rinn commented
We don't currently disable acquiring from closet so that wouldn't make a difference. My wrapper script put them in my display but that's really dumb, also if I remember correctly i think fixed the issue with long maximize strings in mafia a while ago.

2022-09-19 19:50 UTC, Rinn commented
I had some issues due to a power outage so I'll test this again after another run in a few days.

2022-09-19 20:50 UTC, docrostov commented
@phulin gurbo is lit

2022-09-20 16:32 UTC, horrible-little-slime requested changes
One tiny change

2022-09-20 16:32 UTC, horrible-little-slime commented on src/session.ts
> +      return historicalPrice(item) * 0.9;
```suggestion
      const isMallMin = historicalPrice(item) === Math.min(100, 2 * autosellPrice(item));
      return isMallMin ? autosellPrice(item) : 0.9 * historicalPrice(item);
```

2022-09-20 17:00 UTC, horrible-little-slime approved these changes
yell heah

2022-09-20 17:01 UTC, merged