Support Lava Dogs
Loathing-Associates-Scripting-Society/garbage-collector pull request #1911
Opened 2024-06-01 10:45 UTC by Shiverwarp

2024-06-02 15:40 UTC, horrible-little-slime commented on packages/garbo/src/lib.ts
> +  if (get("_lastCombatLost")) {
How does this interact with `Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl`?

2024-06-03 02:03 UTC, horrible-little-slime commented on packages/garbo/src/resources/doghouse.ts
> +      7 * get("valueOfAdventure") +
I don't think 7 is right? I'm pretty sure the ghost dog adventure is free. I can check in a sec.

2024-06-03 02:07 UTC, horrible-little-slime commented on packages/garbo/src/resources/doghouse.ts
> +      7 * get("valueOfAdventure") +
I zoned out and did not check.

2024-06-03 02:08 UTC, horrible-little-slime commented on packages/garbo/src/tasks/barfTurn.ts
> +    ...lavaDogs(() => willDrunkAdventure()),
oh na you're good

2024-06-03 02:09 UTC, horrible-little-slime commented on packages/garbo/src/tasks/post/index.ts
> +      realmAvailable("hot"),
It's not performance, I just don't like separating cause from effect.

2024-06-03 17:28 UTC, horrible-little-slime requested changes
Did some spading, alllllmost there, just one last round of changes

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/resources/doghouse.ts
> +      7 * get("valueOfAdventure") +
Having done some spading, _this_ one should be 6

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/tasks/barfTurn.ts
> +        ? clamp(7 - $location`The Bubblin' Caldera`.turnsSpent, 0, 7)
This remains 7

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/resources/doghouse.ts
> +    $location`The Bubblin' Caldera`.turnsSpent >= 7 ||
This remains 7

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/resources/doghouse.ts
> +    $location`The Bubblin' Caldera`.turnsSpent >= 7 ||
(or becomes > 6)

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/tasks/barfTurn.ts
> +    },
```suggestion
    prepare: () => {
      const metalValue = get("_volcanoSuperduperheatedMetal") ? garboValue($item`superheated metal`) : sum([[$item`superheated metal`, 0.95], [$item`superduperheated metal`, 0.05]], ([item, rate]) => rate * garboValue(item));
      if (metalValue > mallPrice($item`heat-resistant sheet metal`)) {
        acquire(
          1,
          $item`heat-resistant sheet metal`,
          metalValue,
        );
      }
    },
```

2024-06-03 17:28 UTC, horrible-little-slime commented on packages/garbo/src/tasks/barfTurn.ts
> +    },
This'll fail linting at first because it needs to be broken up, so you can pull the changes and lint and then push :-/

2024-06-04 18:46 UTC, horrible-little-slime approved these changes
Approved.

@Shiverwarp merge this after running it one last time

2024-06-04 18:47 UTC, horrible-little-slime commented on packages/garbo/src/resources/clanVIP.ts
> +    // FIXME getClanID returns a clan even if you aren't currently in one, as long as you were ever in a clan.
I am extremely fine with this never getting fixed btw.

That being said, I'm a little surprised it's automatically coercing this to a boolean.

2024-06-06 18:15 UTC, Rinn approved these changes

2024-06-07 09:11 UTC, merged