drinkSafe instead of drink
Loathing-Associates-Scripting-Society/garbage-collector pull request #332
Opened 2021-08-06 04:54 UTC by Rinn

Just replacing two calls to mafia drink with drinkSafe

2021-08-06 05:06 UTC, horrible-little-slime approved these changes

2021-08-06 05:08 UTC, horrible-little-slime requested changes
I changed my mind, and no longer approve of this; drinkSafe calls acquire, which then checks for a price cap. You need to either edit acquire to not blow up for pilsners, or continue not using drinkSafe for the times we drink pilsners

2021-08-06 06:28 UTC, Rinn commented
oh i see what you mean, I'll fix that

2021-08-07 21:11 UTC, horrible-little-slime commented on src/diet.ts
> +      globalOptions.ascending &&
:)

2021-08-07 21:13 UTC, horrible-little-slime approved these changes
I'd like to see `fillLiverAstralPilsner();` used where we start filling up with turkey, regardless of whether we're ascending. That may generally be the best place for it.

2021-08-09 19:02 UTC, merged